# Change these first
owner: ajainvivek # Your GitHub organization or username, where this repository lives
repo: Compensa # The name of this repository

sites:
  - name: Account API
    url: https://account.api.compensa.dev/healthcheck
  - name: Expense API
    url: https://expense.api.compensa.dev/healthcheck
  - name: Benefit API
    url: https://benefit.api.compensa.dev/healthcheck
  - name: Reward API
    url: https://reward.api.compensa.dev/healthcheck

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
